project:
  type: website
  output-dir: docs

website:
  title: "Ag-vision"
  navbar:
    logo: logo.png
    right:
      - text: "AI for Agriculture 2023"
        menu: 
          - text: 'Kaggle-2023 Part 1'
            file: index.qmd
          - text: 'Kaggle-2023 Part 2'
            file: kaggle2023.qmd
      - text: "AI for Agriculture 2022"
        menu:
          - text: 'Kaggle-2022'
            file: kaggle2022.qmd
          - text:  'Conference-2022'
            file: Conf2022.qmd
      - about.qmd

format:
  html:
    theme: Cosmo
    css: styles.css
    toc: true



