project:
  type: website
  output-dir: docs

website:
  title: "Ag-vision"
  navbar:
    logo: logo.png
    right:
      - text: "AI for Agriculture 2023"
        menu: 
          - kaggle2023.qmd
      - text: "AI for Agriculture 2022"
        menu:
          - kaggle2022.qmd
          - Conf2022.qmd
      - about.qmd

format:
  html:
    theme: Cosmo
    css: styles.css
    toc: true



